### ISSUE TITLE
Does unofficial Yocto build need this?

### ISSUE THREAD

**Issue by andy-shev** [majenkotech/IntelFixes#1]
@htot
Have you seen this? What do you think?

**Comment by htot** [comment]
Not exactly sure. If this is 'just' the poky sdk, then it is something yocto already builds for us:
https://htot.github.io/meta-intel-edison/3-Building-the-SDK.html

**Comment by andy-shev** [comment]
@htot 
I didn't look inside, though it sounds to me that it contains stuff that Arduino SDK uses somehow.

**Comment by htot** [comment]
I traced the files back to https://downloadcenter.intel.com/download/26997/Intel-Edison-Cross-Compiler-Toolchain?product=84571 which are afaict indeed the pre-built cross compiler tool chain. This is exactly what we already build, except we build a much newer tool chain (Yocto thud <-> dizzy).

There is another sdk see https://downloadcenter.intel.com/product/84571/Intel-Edison-Kit-for-Arduino- with docker and Eclipse stuff that I never used.

**Comment by andy-shev** [comment]
I see, so, for newest Yocto these scripts are not needed AFAIU. Thanks for elaboration. I'm closing this now.
