### ISSUE TITLE
Intel scripts no longer with python3 as default python

### ISSUE THREAD

**Issue by deepcoder** [majenkotech/IntelFixes#2]
FYI...
'''
Setting it up.../tmp/tmp.f336iLg5Hu/relocate_sdk.sh /home/user/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0/i586/relocate_sdk.sh
  File "/home/user/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0/i586/relocate_sdk.py", line 98
    print "ERROR: could not relocate %s, interp size = %i and %i is needed." % (elf_file_name, p_memsz, len(new_dl_path) + 1)
          ^
SyntaxError: invalid syntax
SDK could not be set up. Relocate script failed. Abort!
'''

**Comment by deepcoder** [comment]
Seems if you reinstall python2 and they make following change, you can manually run 

```

~/.arduino15/packages/Intel/tools/i586-poky-linux-uclibc/1.6.2+1.0/i586/relocate_sdk.py

change
#!/usr/bin/env python
--to--
#!/usr/bin/env python2

# run
./install_script.sh
```

**Comment by majenkotech** [comment]
Nice find. Thanks.

**Comment by acimmarusti** [comment]
@deepcoder and @majenkotech I know this is an old post, but for FWIW, this pull request: #4 would bring support for `python3` (especially important now that `python2` has all but dissapeared from the most popular and updated linux distributions)
